package com.taskbuddy.entities;
// Generated 8 Dec, 2016 8:35:06 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Logininfo generated by hbm2java
 */
@Entity
@Table(name = "LOGININFO", catalog = "taskbuddy", uniqueConstraints = @UniqueConstraint(columnNames = { "EMAIL",
		"USERNAME" }))
public class Logininfo implements java.io.Serializable {

	private Integer loginid;
	@NotEmpty(message="username cannot be empty.")
	private String username;
	private String email;
	@NotEmpty(message="password cannot be empty.")
	private String password;
	private String role;
	private Set<Userinfo> userinfos = new HashSet<Userinfo>(0);
	private Set<Taskerinfo> taskerinfos = new HashSet<Taskerinfo>(0);
	private Set<Operation> operations = new HashSet<Operation>(0);

	public Logininfo() 
	{
		this("","","","");
	}

	public Logininfo(String username, String email, String password, String role) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.role = role;
	}

	public Logininfo(String username, String email, String password, String role, Set<Userinfo> userinfos,
			Set<Taskerinfo> taskerinfos, Set<Operation> operations) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.role = role;
		this.userinfos = userinfos;
		this.taskerinfos = taskerinfos;
		this.operations = operations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY) //allows database to automatically assign id to object when its row is inserted

	@Column(name = "LOGINID", unique = true, nullable = false)
	public Integer getLoginid() {
		return this.loginid;
	}

	public void setLoginid(Integer loginid) {
		this.loginid = loginid;
	}

	@Column(name = "USERNAME", nullable = false, length = 40)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "EMAIL", nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", nullable = false, length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ROLE", nullable = false, length = 40)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "logininfo")
	public Set<Userinfo> getUserinfos() {
		return this.userinfos;
	}

	public void setUserinfos(Set<Userinfo> userinfos) {
		this.userinfos = userinfos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "logininfo")
	public Set<Taskerinfo> getTaskerinfos() {
		return this.taskerinfos;
	}

	public void setTaskerinfos(Set<Taskerinfo> taskerinfos) {
		this.taskerinfos = taskerinfos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "logininfo")
	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

	@Override
	public String toString() {
		return "Logininfo [loginid=" + loginid + ", username=" + username + ", email=" + email + ", password="
				+ password + ", role=" + role + "]";
	}

	
}
