package com.taskbuddy.entities;
// Generated 8 Dec, 2016 8:35:06 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Taskerinfo generated by hbm2java
 */
@Entity
@Table(name = "TASKERINFO", catalog = "taskbuddy")
public class Taskerinfo implements java.io.Serializable {

	private Integer taskerid;
	private Logininfo logininfo;
	private String category;
	private double charge;
	private boolean status;
	private Set<Operation> operations = new HashSet<Operation>(0);

	public Taskerinfo() {
	}

	public Taskerinfo(Logininfo logininfo, String category, double charge, boolean status) {
		this.logininfo = logininfo;
		this.category = category;
		this.charge = charge;
		this.status = status;
	}

	public Taskerinfo(Logininfo logininfo, String category, double charge, boolean status, Set<Operation> operations) {
		this.logininfo = logininfo;
		this.category = category;
		this.charge = charge;
		this.status = status;
		this.operations = operations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TASKERID", unique = true, nullable = false)
	public Integer getTaskerid() {
		return this.taskerid;
	}

	public void setTaskerid(Integer taskerid) {
		this.taskerid = taskerid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LOGINID", nullable = false)
	public Logininfo getLogininfo() {
		return this.logininfo;
	}

	public void setLogininfo(Logininfo logininfo) {
		this.logininfo = logininfo;
	}

	@Column(name = "CATEGORY", nullable = false, length = 30)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "CHARGE", nullable = false, precision = 7)
	public double getCharge() {
		return this.charge;
	}

	public void setCharge(double charge) {
		this.charge = charge;
	}

	@Column(name = "STATUS", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "taskerinfo")
	public Set<Operation> getOperations() {
		return this.operations;
	}

	public void setOperations(Set<Operation> operations) {
		this.operations = operations;
	}

	@Override
	public String toString() {
		return "Taskerinfo [taskerid=" + taskerid + ", category=" + category + ", charge="
				+ charge + ", status=" + status + "]";
	}
	
}
