package com.taskbuddy.entities;
// Generated 8 Dec, 2016 8:35:06 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userinfo generated by hbm2java
 */

@Entity
@Table(name = "USERINFO", catalog = "taskbuddy")
public class Userinfo implements java.io.Serializable {

	private Integer userid;
	private Logininfo logininfo;
	private String userfirstname;
	private String userlastname;
	private String gender;
	private String contactno;
	private String address;
	private String location;
	private int pincode;
	private String city;
	private String state;
	private String country;

	public Userinfo() 
	{
		this(null,"","","","","","",0,"","","");
	}

	public Userinfo(Logininfo logininfo, String userfirstname, String userlastname, String gender, String contactno,
			String address, String location, int pincode, String city, String state, String country) {
		this.logininfo = logininfo;
		this.userfirstname = userfirstname;
		this.userlastname = userlastname;
		this.gender = gender;
		this.contactno = contactno;
		this.address = address;
		this.location = location;
		this.pincode = pincode;
		this.city = city;
		this.state = state;
		this.country = country;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "USERID", unique = true, nullable = false)
	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LOGINID", nullable = false)
	public Logininfo getLogininfo() {
		return this.logininfo;
	}

	public void setLogininfo(Logininfo logininfo) {
		this.logininfo = logininfo;
	}

	@Column(name = "USERFIRSTNAME", nullable = false, length = 45)
	public String getUserfirstname() {
		return this.userfirstname;
	}

	public void setUserfirstname(String userfirstname) {
		this.userfirstname = userfirstname;
	}

	@Column(name = "USERLASTNAME", nullable = false, length = 45)
	public String getUserlastname() {
		return this.userlastname;
	}

	public void setUserlastname(String userlastname) {
		this.userlastname = userlastname;
	}

	@Column(name = "GENDER", nullable = false, length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "CONTACTNO", nullable = false, length = 45)
	public String getContactno() {
		return this.contactno;
	}

	public void setContactno(String contactno) {
		this.contactno = contactno;
	}

	@Column(name = "ADDRESS", nullable = false, length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "LOCATION", nullable = false, length = 20)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "PINCODE", nullable = false)
	public int getPincode() {
		return this.pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	@Column(name = "CITY", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", nullable = false, length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COUNTRY", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Override
	public String toString() {
		return "Userinfo [userid=" + userid + ", logininfo=" + logininfo + ", userfirstname=" + userfirstname
				+ ", userlastname=" + userlastname + ", gender=" + gender + ", contactno=" + contactno + ", address="
				+ address + ", location=" + location + ", pincode=" + pincode + ", city=" + city + ", state=" + state
				+ ", country=" + country + "]";
	}
		
}
